apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-test-svc.myapp1
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
  - host: demo1.hit.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: http-test-svc
          servicePort: 80
